# Generated by Django 2.1.2 on 2018-11-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20181104_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='mark',
            name='amount',
            field=models.FloatField(),
        ),
    ]
